plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
remote_theme: BDHU/minimalist
title: Mehmet Galioglu
logo: /assets/img/pp.jpg
description: Test Automation Engineer
show_downloads: false
color-scheme: dark

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/MehmetGalioglu
  - name: Email
    icon: <i class="fa-solid fa-pen"></i>
    link: mailto:mehmetgalioglu@gmail.com
    
github: [metadata]
